name: docker-caddy
inputs:
  version:
    required: true
    default: false
  upstream:
    required: true
    default: false
  downstream:
    required: false
    default: false
runs:
  using: composite
  steps:
    - env:
        INPUTS_UPSTREAM: ${{ inputs.upstream }}
        INPUTS_VERSION: ${{ inputs.version }}
        INPUTS_DOWNSTREAM: ${{ inputs.downstream }}
      shell: bash
      run: |
        OLD_VER=$(grep '## v' dockers/${INPUTS_UPSTREAM}/README.md | tail -n +2  | head -n 1 | cut -dv -f2)

        # Update Dockerfile
        sed -i "s/$OLD_VER/${INPUTS_VERSION}/" dockers/${INPUTS_DOWNSTREAM}/Dockerfile
        if [ ! -z "$(git status --porcelain)" ]; then
          # Add an entry to README.md
          head -n 2 dockers/${INPUTS_DOWNSTREAM}/README.md > temp.md
          grep -m 1 '## v' dockers/${INPUTS_DOWNSTREAM}/README.md | cut -d. -f1-2 | tr -d '\n' >> temp.md
          echo -n . >> temp.md
          grep -m 1 '## v' dockers/${INPUTS_DOWNSTREAM}/README.md | cut -d. -f3 | awk '{print $1 + 1}' >> temp.md
          echo >> temp.md
          echo '- Bump femiwiki/${INPUTS_UPSTREAM} to v${INPUTS_VERSION}' >> temp.md
          echo >> temp.md
          tail -n +3 dockers/${INPUTS_DOWNSTREAM}/README.md >> temp.md
          mv -f temp.md dockers/${INPUTS_DOWNSTREAM}/README.md
        fi
