name: docker-mediawiki
inputs:
  version:
    required: true
  push:
    required: false
    default: false
runs:
  using: composite
  steps:
    - uses: docker/build-push-action@v6
      with:
        context: '{{ defaultContext }}:dockers/mediawiki'
        platforms: linux/amd64,linux/arm64
        cache-from: ghcr.io/femiwiki/mediawiki:latest
        load: false
        push: ${{ inputs.push }}
        tags: |
          ghcr.io/femiwiki/mediawiki:latest
          ghcr.io/femiwiki/mediawiki:${{ inputs.version }}
