version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - 'femiwiki/reviewer'

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - 'femiwiki/reviewer'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - 'femiwiki/reviewer'

  - package-ecosystem: 'bundler'
    directory: '/extension-installer'
    schedule:
      interval: monthly
    reviewers:
      - 'femiwiki/reviewer'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - 'femiwiki/reviewer'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-minor'
          - 'version-update:semver-patch'
