version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/'
    commit-message:
      prefix: build
      include: scope
    schedule:
      interval: monthly
    reviewers:
      - 'femiwiki/reviewer'
    cooldown:
      default-days: 7

  - package-ecosystem: 'composer'
    directory: '/'
    commit-message:
      prefix: build
      include: scope
    schedule:
      interval: monthly
    reviewers:
      - 'femiwiki/reviewer'
    cooldown:
      default-days: 7

  - package-ecosystem: 'npm'
    directory: '/'
    commit-message:
      prefix: build
      include: scope
    schedule:
      interval: monthly
    reviewers:
      - 'femiwiki/reviewer'
    cooldown:
      default-days: 7

  - package-ecosystem: 'bundler'
    directory: '/dockers/femiwiki-extensions/extension-installer'
    commit-message:
      prefix: build
      include: scope
    schedule:
      interval: monthly
    reviewers:
      - 'femiwiki/reviewer'
    cooldown:
      default-days: 7

  - package-ecosystem: 'github-actions'
    directory: '/'
    commit-message:
      prefix: build
      include: scope
    schedule:
      interval: monthly
    reviewers:
      - 'femiwiki/reviewer'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-minor'
          - 'version-update:semver-patch'
    cooldown:
      default-days: 7
