version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    default_reviewers:
      - "femiwiki/reviewer"

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'
    default_reviewers:
      - "femiwiki/reviewer"

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    default_reviewers:
      - "femiwiki/reviewer"

  - package-ecosystem: 'bundler'
    directory: '/extension-installer'
    schedule:
      interval: 'daily'
    default_reviewers:
      - "femiwiki/reviewer"

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    default_reviewers:
      - "femiwiki/reviewer"
