os: linux
dist: xenial
git:
  quiet: true
  depth: 3

# PHP
language: php
php: '7.2'
cache:
  directories:
    - vendor

env:
  global:
    # Maximum iteration limit for loop
    - LOOP_LIMIT=300

services:
  - docker

jobs:
  include:
    #
    # LocalSettings.php 코드 lint
    #
    - name: lint
      install:
        - composer install --prefer-source --quiet --no-interaction
      script:
        - composer test


    #
    # 미디어위키 도커 이미지가 정상적으로 실행되는지 확인
    #
    - name: docker
      before_script:
        # Edit configuration
        - |
          mv configs/secret.php.example configs/secret.php;
          printf 'const DEBUG_MODE = 'localhost';\nrequire_once "$IP/includes/DevelopmentSettings.php";\n' >> configs/LocalSettings.php;
      script:
        # Build image
        - docker build --tag femiwiki/mediawiki .
        # Initialize docker swarm and start services
        - docker swarm init
        - docker stack deploy -c development.yml mediawiki
        # Access localhost until success
        - |
            printf 'Waiting for http...'
            COUNTER=0;
            until [ "$(curl -Ls localhost 2>/dev/null)" ]; do
              sleep 1;
              printf '.';
              (( COUNTER++ ));
              if [ $COUNTER -gt $LOOP_LIMIT ]; then
                printf '\n';
                echo 'Failed to connect to localhost';
                travis_terminate 1;
              fi
            done; printf '\n'
        # Check if the container is still up
        - test -z "$(docker service ps -qf 'desired-state=Shutdown' mediawiki_fastcgi)"
        # Try to access the mediawiki
        - curl -sSLvo /dev/null localhost || docker service logs mediawiki_fastcgi
      after_success:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL
      after_failure:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh failure $WEBHOOK_URL
