version: '3.5'
services:
  tweetbot:
    image: femiwiki/tweetbot
    volumes:
      - /srv/tweetbot:/var/tweetbot
    env_file:
      - secret
  ranking-bot:
    image: femiwiki/rankingbot
    env_file:
      - secret
  backupbot:
    image: femiwiki/backupbot
    env_file:
      - secret
    networks:
      hostnet: {}

networks:
  hostnet:
    external: true
    name: host
