# This compose file is for develompent and build testing
version: '3'
services:
  http:
    image: ghcr.io/femiwiki/femiwiki:latest
    command: caddy run
    ports:
      - 8080:8080
    volumes:
      - caddy:/etc/caddycerts
      - ./development/Caddyfile:/srv/femiwiki.com/Caddyfile:ro
    environment:
      - CADDYPATH=/etc/caddycerts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      options:
        max-size: '100m'
  fastcgi:
    image: ghcr.io/femiwiki/femiwiki:latest
    volumes:
      - ./development/site-list.xml:/a/site-list.xml:ro
      - l18n_cache:/tmp/cache
    environment:
      MEDIAWIKI_DEBUG_MODE: 'true'
      MEDIAWIKI_SERVER: http://127.0.0.1:8080
      WG_INTERNAL_SERVER: http://http:8080
      WG_DB_SERVER: mysql
      WG_DB_USER: mediawiki
      WG_DB_PASSWORD: mediawiki
      WG_MEMCACHED_SERVERS: http:8080
      WG_BOUNCE_HANDLER_INTERNAL_IPS: 127.0.0.1
      WG_O_AUTH_2_PRIVATE_KEY: "------BEGIN RSA PRIVATE KEY-----\n------END RSA PRIVATE KEY-----"
    depends_on:
      - mysql
      - memcached
  mysql:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=localfemiwikipassword
      - MYSQL_DATABASE=femiwiki
      - MYSQL_USER=mediawiki
      - MYSQL_PASSWORD=mediawiki
  memcached:
    image: memcached:1-alpine

volumes:
  database:
  caddy:
  l18n_cache:
