version: '3'
services:
  http:
    image: ghcr.io/femiwiki/mediawiki:latest
    command: caddy run
    ports:
      - 80:80
      - 443:443
    volumes:
      # Overwrite production Caddyfile
      - ./caddy/Caddyfile.dev:/srv/femiwiki.com/Caddyfile:ro
      - caddy:/etc/caddycerts
    environment:
      - CADDYPATH=/etc/caddycerts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      options:
        max-size: "100m"
  fastcgi:
    image: ghcr.io/femiwiki/mediawiki:latest
    volumes:
      - ./configs:/a:ro
      - l18n_cache:/tmp/cache
      ## 스킨 등 개발할 때엔 아래 라인을 주석해제
      # - ../skin:/srv/femiwiki.com/skins/Femiwiki
      # - ../AchievementBadges:/srv/femiwiki.com/extensions/AchievementBadges
      # - ../CategoryIntersectionSearch:/srv/femiwiki.com/extensions/CategoryIntersectionSearch
      # - ../FacetedCategory:/srv/femiwiki.com/extensions/FacetedCategory
      # - ../Sanctions:/srv/femiwiki.com/extensions/Sanctions
      # - ../UnifiedExtensionForFemiwiki:/srv/femiwiki.com/extensions/UnifiedExtensionForFemiwiki
  parsoid:
    image: ghcr.io/femiwiki/parsoid:latest
    environment:
      - MEDIAWIKI_LINTING=true
      - MEDIAWIKI_APIS_DOMAIN=localhost
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=localfemiwikipassword
      - MYSQL_DATABASE=femiwiki
      - MYSQL_USER=DB_USERNAME # secret.php.example에 적힌 기본값
      - MYSQL_PASSWORD=DB_PASSWORD # secret.php.example에 적힌 기본값
    networks:
      default:
        aliases:
          - DB_HOSTNAME # secret.php.example에 적힌 기본값
  memcached:
    image: memcached:1-alpine
    networks:
      default:
        aliases:
          - MEMCACHED_HOSTNAME # secret.php.example에 적힌 기본값
  restbase:
    image: ghcr.io/femiwiki/restbase:latest
    environment:
      - MEDIAWIKI_APIS_DOMAIN=localhost
    networks:
      default:
        aliases:
          - RESTBASE_HOSTNAME # secret.php.example에 적힌 기본값
  mathoid:
    image: ghcr.io/femiwiki/mathoid:latest

volumes:
  database:
  caddy:
  l18n_cache:
