version: '3'
services:
  http:
    image: ghcr.io/femiwiki/caddy:1.0.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile.dev:/etc/Caddyfile:ro
      - files:/srv/femiwiki.com
      - caddy:/etc/caddycerts
    environment:
      - CADDYPATH=/etc/caddycerts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  fastcgi:
    image: ghcr.io/femiwiki/mediawiki:latest
    volumes:
      - ./configs:/a:ro
      - files:/srv/femiwiki.com
      - l18n_cache:/tmp/cache
      ## 스킨 등 개발할 때엔 아래 라인을 주석해제
      # - ../skin:/srv/femiwiki.com/skins/Femiwiki
      # - ../UnifiedExtensionForFemiwiki:/srv/femiwiki.com/extensions/UnifiedExtensionForFemiwiki
  parsoid:
    image: ghcr.io/femiwiki/parsoid:2020-09-05T10-03-ae442600
    environment:
      - MEDIAWIKI_LINTING=true
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=localfemiwikipassword
      - MYSQL_DATABASE=femiwiki
      - MYSQL_USER=DB_USERNAME # secret.php.example에 적힌 기본값
      - MYSQL_PASSWORD=DB_PASSWORD # secret.php.example에 적힌 기본값
    networks:
      default:
        aliases:
          - DB_HOSTNAME # secret.php.example에 적힌 기본값
  memcached:
    image: memcached:1-alpine
    networks:
      default:
        aliases:
          - MEMCACHED_HOSTNAME # secret.php.example에 적힌 기본값
  restbase:
    image: ghcr.io/femiwiki/restbase:2020-09-05T10-04-5dcdc8b6
    networks:
      default:
        aliases:
          - RESTBASE_HOSTNAME # secret.php.example에 적힌 기본값
  mathoid:
    image: wikimedia/mathoid:bad5ec8d4

volumes:
  files:
  database:
  caddy:
  l18n_cache:
