version: '3'
services:
  http:
    image: ghcr.io/femiwiki/mediawiki:latest
    command: caddy run
    ports:
      - 8080:8080
    volumes:
      - caddy:/etc/caddycerts
      - ./development/Caddyfile:/srv/femiwiki.com/Caddyfile:ro
    environment:
      - CADDYPATH=/etc/caddycerts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      options:
        max-size: '100m'
  fastcgi:
    image: ghcr.io/femiwiki/mediawiki:latest
    volumes:
      # Mount secret.php, LocalSettings.php and site-list.xml
      - ./development:/a:ro
      - l18n_cache:/tmp/cache
      ## 스킨 등 개발할 때엔 아래 라인을 주석해제
      # - ../skin:/srv/femiwiki.com/skins/Femiwiki
      # - ../AchievementBadges:/srv/femiwiki.com/extensions/AchievementBadges
      # - ../DiscordNotifications:/srv/femiwiki.com/extensions/DiscordNotifications
      # - ../FacetedCategory:/srv/femiwiki.com/extensions/FacetedCategory
      # - ../Sanctions:/srv/femiwiki.com/extensions/Sanctions
      # - ../UnifiedExtensionForFemiwiki:/srv/femiwiki.com/extensions/UnifiedExtensionForFemiwiki
    environment:
      - MEDIAWIKI_SERVER=http://127.0.0.1:8080
      - MEDIAWIKI_DOMAIN_FOR_NODE_SERVICE=localhost
      - MEDIAWIKI_DEBUG_MODE=1
      # - MEDIAWIKI_SKIP_INSTALL=1
      # - MEDIAWIKI_SKIP_UPDATE=1
      # - MEDIAWIKI_SKIP_IMPORT_SITES=1
    depends_on:
      - mysql
      - memcached
  parsoid:
    image: ghcr.io/femiwiki/parsoid:latest
    environment:
      - MEDIAWIKI_LINTING=true
      - MEDIAWIKI_APIS_URI=http://http:8080/api.php
      - MEDIAWIKI_APIS_DOMAIN=localhost
    depends_on:
      - fastcgi
      - http
  mysql:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=localfemiwikipassword
      - MYSQL_DATABASE=femiwiki
      - MYSQL_USER=DB_USERNAME # secret.php.example에 적힌 기본값
      - MYSQL_PASSWORD=DB_PASSWORD # secret.php.example에 적힌 기본값
    networks:
      default:
        aliases:
          - DB_HOSTNAME # secret.php.example에 적힌 기본값
  memcached:
    image: memcached:1-alpine
  restbase:
    image: ghcr.io/femiwiki/restbase:latest
    environment:
      - MEDIAWIKI_APIS_URI=http://http:8080/api.php
      - MEDIAWIKI_APIS_DOMAIN=localhost
  mathoid:
    image: ghcr.io/femiwiki/mathoid:latest

volumes:
  database:
  caddy:
  l18n_cache:
