version: '3'
services:
  http:
    image: joshix/caddy
    ports:
      - 80:80
    volumes:
      - ./caddy:/var/www/html:ro
      - files:/srv/femiwiki.com
  fastcgi:
    image: femiwiki/mediawiki
    volumes:
      - ./configs/LocalSettings.php:/a/LocalSettings.php:ro
      - ./configs/secret.php:/a/secret.php:ro
      - files:/srv/femiwiki.com
    env_file:
      - configs/env
  parsoid:
    image: femiwiki/parsoid
  restbase:
    image: femiwiki/restbase
    ports:
      - 7231:7231
volumes:
  files:
