# This compose file is for develompent and build testing
version: '3'
services:
  http:
    image: ghcr.io/femiwiki/mediawiki:latest
    command: caddy run
    ports:
      - 8080:8080
    volumes:
      - caddy:/etc/caddycerts
      - ./dockers/femiwiki/development/Caddyfile:/srv/femiwiki.com/Caddyfile:ro
    environment:
      - CADDYPATH=/etc/caddycerts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      options:
        max-size: '100m'
  fastcgi:
    image: ghcr.io/femiwiki/mediawiki:latest
    volumes:
      # Mount secret.php, LocalSettings.php and site-list.xml
      - ./dockers/femiwiki/development:/a:ro
      - l18n_cache:/tmp/cache
    environment:
      - MEDIAWIKI_SERVER=http://127.0.0.1:8080
      - MEDIAWIKI_DEBUG_MODE=1
    depends_on:
      - mysql
      - memcached
  mysql:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=localfemiwikipassword
      - MYSQL_DATABASE=femiwiki
      - MYSQL_USER=DB_USERNAME # secret.php.example에 적힌 기본값
      - MYSQL_PASSWORD=DB_PASSWORD # secret.php.example에 적힌 기본값
    networks:
      default:
        aliases:
          - DB_HOSTNAME # secret.php.example에 적힌 기본값
  memcached:
    image: memcached:1-alpine

volumes:
  database:
  caddy:
  l18n_cache:
