# 스킨 등 개발할 때엔 아래 라인 중 필요한 것을 주석해제 후 다음과 같이 실행:
#   docker stack deploy --prune -c docker-compose.yml -c docker-compose.override.yml mediawiki
# 혹은:
#   docker-compose up
version: '3'
services:
  # http:
  #   volumes:
  #     - ../Femiwiki:/srv/femiwiki.com/skins/Femiwiki
  # fastcgi:
  #   volumes:
  #     - ../Femiwiki:/srv/femiwiki.com/skins/Femiwiki
  #     - ../AchievementBadges:/srv/femiwiki.com/extensions/AchievementBadges
  #     - ../DiscordRCFeed:/srv/femiwiki.com/extensions/DiscordRCFeed
  #     - ../FacetedCategory:/srv/femiwiki.com/extensions/FacetedCategory
  #     - ../PageViewInfoGA:/srv/femiwiki.com/extensions/PageViewInfoGA
  #     - ../Sanctions:/srv/femiwiki.com/extensions/Sanctions
  #     - ../UnifiedExtensionForFemiwiki:/srv/femiwiki.com/extensions/UnifiedExtensionForFemiwiki
  #   environment:
  #     - MEDIAWIKI_SKIP_INSTALL=1
  #     - MEDIAWIKI_SKIP_UPDATE=1
  #     - MEDIAWIKI_SKIP_IMPORT_SITES=1
