# This compose file is for develompent and build testing
version: '3'
services:
  http:
    image: ghcr.io/femiwiki/femiwiki:latest
    command: caddy run
    ports:
      - 8080:8080
    volumes:
      - caddy:/etc/caddycerts
      - ./development/Caddyfile:/srv/femiwiki.com/Caddyfile:ro
    environment:
      - CADDYPATH=/etc/caddycerts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      options:
        max-size: '100m'
  fastcgi:
    image: ghcr.io/femiwiki/femiwiki:latest
    volumes:
      # Mount secrets.php, LocalSettings.php and site-list.xml
      - ./development:/a:ro
      - l18n_cache:/tmp/cache
    environment:
      MEDIAWIKI_DEBUG_MODE: 'true'
      MEDIAWIKI_SERVER: http://127.0.0.1:8080
      WG_INTERNAL_SERVER: http://http:8080
      WG_DB_SERVER: mysql
      WG_DB_USER: DB_USERNAME
      WG_DB_PASSWORD: DB_PASSWORD
      WG_MEMCACHED_SERVERS: http:8080
    # https://github.com/docker/cli/issues/3880
    depends_on:
      - mysql
      - memcached
  mysql:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=localfemiwikipassword
      - MYSQL_DATABASE=femiwiki
      - MYSQL_USER=DB_USERNAME # secrets.php.example에 적힌 기본값
      - MYSQL_PASSWORD=DB_PASSWORD # secrets.php.example에 적힌 기본값
    networks:
      default:
        aliases:
          - DB_HOSTNAME # secrets.php.example에 적힌 기본값
  memcached:
    image: memcached:1-alpine

volumes:
  database:
  caddy:
  l18n_cache:
