#!/bin/bash
set -euo pipefail; IFS=$'\n\t '

# Below extensions have no submodule (at least in REL1_31)
# So we can download their tar.gz files simply.
EXTENSIONS_FROM_GERRIT_WITHOUT_SUBMODULE=" \
  TemplateData \
  TwoColConflict \
  RevisionSlider \
  Echo \
  Thanks \
  Flow \
  Scribunto \
  TemplateStyles \
  Disambiguator \
  CreateUserPage \
  AbuseFilter \
  CheckUser \
  UserMerge \
  CodeMirror \
  CharInsert \
  Description2 \
  OpenGraphMeta \
  PageImages \
  Josa \
  HTMLTags \
  BetaFeatures \
  "

# Extensions has no submodules too. But they are all on github/Femiwiki.
EXTENSIONS_MADE_BY_FEMIWIKI="\
  Sanctions \
  CategoryIntersectionSearch \
  FacetedCategory \
  UnifiedExtensionForFemiwiki \
  "

# Below extensions treated specially because of their complex download URL
OTHER_EXTENSIONS=" \
  AWS \
  EmbedVideo \
  SimpleMathJax \
  "

# Below extensions will be cloned by git command.
EXTENSIONS_FROM_GERRIT_WITH_SUBMODULE=" \
  VisualEditor \
  Widgets \
  "

ALL_EXTENSIONS=" \
  $EXTENSIONS_FROM_GERRIT_WITH_SUBMODULE \
  $EXTENSIONS_FROM_GERRIT_WITHOUT_SUBMODULE \
  $EXTENSIONS_MADE_BY_FEMIWIKI \
  $OTHER_EXTENSIONS \
  "

# Download extensions can be download using aria2
{ \
  for extension in $EXTENSIONS_FROM_GERRIT_WITHOUT_SUBMODULE; do
    echo "https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/$extension/+archive/${MEDIAWIKI_BRANCH}.tar.gz";
    echo " out=$extension.tar.gz"
  done

  for extension in $EXTENSIONS_MADE_BY_FEMIWIKI; do
    echo "https://github.com/femiwiki/$extension/archive/master.tar.gz"
    echo " out=$extension.tar.gz"
  done

  # Extensions with complex download URL
  # AWS (v0.10.0)
  echo "https://github.com/edwardspec/mediawiki-aws-s3/archive/v0.10.0.tar.gz";
  echo " out=AWS.tar.gz";
  # EmbedVideo
  echo "https://github.com/HydraWiki/mediawiki-embedvideo/archive/v2.7.4.tar.gz";
  echo " out=EmbedVideo.tar.gz";
  # SimpleMathJax
  echo "https://github.com/jmnote/SimpleMathJax/archive/v0.7.3.tar.gz";
  echo " out=SimpleMathJax.tar.gz";

  # Femiwiki skin. Skins should be located in `skins/` directory
  echo "https://github.com/femiwiki/skin/archive/master.tar.gz";
  echo " out=Femiwiki.tar.gz";
} | aria2c --input-file=- --dir=/tmp

# Make directories for each extensions.
for extension in $ALL_EXTENSIONS; do
  mkdir -p "/srv/femiwiki.com/extensions/$extension"
done

# Uncompress tar.gz files.
for extension in $EXTENSIONS_FROM_GERRIT_WITHOUT_SUBMODULE; do
  tar -xzf "/tmp/$extension.tar.gz" --directory "/srv/femiwiki.com/extensions/$extension"
  rm "/tmp/$extension.tar.gz"
done

# Uncompress tar.gz files and strip component
for extension in $EXTENSIONS_MADE_BY_FEMIWIKI $OTHER_EXTENSIONS; do
  tar -xzf "/tmp/$extension.tar.gz" --strip-components=1 --directory "/srv/femiwiki.com/extensions/$extension"
  rm "/tmp/$extension.tar.gz"
done

# Clone extensions existing in gerrit and having submodule
for extension in $EXTENSIONS_FROM_GERRIT_WITH_SUBMODULE; do
  git clone --recurse-submodules --depth 1 "https://gerrit.wikimedia.org/r/p/mediawiki/extensions/$extension" \
  -b "${MEDIAWIKI_BRANCH}" "/srv/femiwiki.com/extensions/$extension"
done

# Install composer dependencies via 'composer update'
for extension in $ALL_EXTENSIONS; do
  if [ -f "/srv/femiwiki.com/extensions/$extension/composer.json" ]; then
    echo "Composing $extension"

    # '/var/www/.composer' is not writable for www-data.
    # Overriding '$COMPOSER_HOME'
    COMPOSER_HOME=/tmp/composer composer update \
      --no-dev \
      --working-dir "/srv/femiwiki.com/extensions/$extension"
  fi
done

# Install femiwiki skin
mkdir -p /srv/femiwiki.com/skins/Femiwiki
tar -xzf /tmp/Femiwiki.tar.gz --strip-components=1 --directory /srv/femiwiki.com/skins/Femiwiki
rm /tmp/Femiwiki.tar.gz

echo 'Installed all extensions and skins'
