version: '3'
services:
  mysql:
    image: mysql:8
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./mysql:/etc/mysql/conf.d:ro
      - /srv/mysql:/var/lib/mysql
  parsoid:
    image: femiwiki/parsoid
  caddy:
    image: joshix/caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy-parsoid:/var/www/html:ro
      - caddy-certificates:/.caddy
volumes:
  caddy-certificates:
