version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - 3306:3306
    volumes:
      - /srv/mysql:/var/lib/mysql
  parsoid:
    image: femiwiki/parsoid
    networks:
      - parsoid-network
  caddy:
    image: joshix/caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy:/var/www/html:ro
      - /srv/caddy:/.caddy:rw
    networks:
      - parsoid-network
networks:
  parsoid-network:
