version: '3'
services:
  http:
    image: ghcr.io/femiwiki/mediawiki:2021-04-07T21-56-e2dc8b41
    command: caddy run
    ports:
      - 80:80
      - 443:443
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - caddy:/etc/caddycerts
    environment:
      - CADDYPATH=/etc/caddycerts
      - FASTCGI_ADDR=fastcgi:9000
      - RESTBASE_ADDR=restbase:7231
      - MEDIAWIKI_SKIP_INSTALL=1
      - MEDIAWIKI_SKIP_UPDATE=1
      - MEDIAWIKI_SKIP_IMPORT_SITES=1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      options:
        max-size: "100m"
  fastcgi:
    image: ghcr.io/femiwiki/mediawiki:2021-04-07T21-56-e2dc8b41
    volumes:
      - ./configs:/a:ro
      # Temporarily mount for hot fix https://github.com/femiwiki/femiwiki/issues/233
      - ./configs:/config/mediawiki:ro
      - l18n_cache:/tmp/cache
      - file_cache:/tmp/file-cache
  parsoid:
    image: ghcr.io/femiwiki/parsoid:2020-12-10T14-51-f84b9d2d
    environment:
      - MEDIAWIKI_LINTING=true
  restbase:
    image: ghcr.io/femiwiki/restbase:2021-03-18T08-44-a48f917b
    environment:
      # Workaround for https://github.com/femiwiki/femiwiki/issues/151
      - MEDIAWIKI_APIS_URI=https://femiwiki.com/api.php
    volumes:
      - /srv/restbase.sqlite3:/srv/restbase/db.sqlite3
  mathoid:
    image: ghcr.io/femiwiki/mathoid:2020-12-09T04-56-c3db867c
  mysql:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/etc/mysql/conf.d:ro
      - /srv/mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  memcached:
    image: memcached:1.6.9-alpine

volumes:
  caddy:
  l18n_cache:
  file_cache:
