version: '3'
services:
  http:
    image: femiwiki/caddy:1.0.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile.prod:/etc/Caddyfile:ro
      - files:/srv/femiwiki.com
      - caddy:/etc/caddycerts
    environment:
      - CADDYPATH=/etc/caddycerts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  fastcgi:
    image: femiwiki/mediawiki:build-21
    volumes:
      - ./configs:/a:ro
      - files:/srv/femiwiki.com
  parsoid:
    image: femiwiki/parsoid:build-0
  ## 잠시 끔. https://github.com/femiwiki/femiwiki/issues/82 참고
  #restbase:
  #  image: femiwiki/restbase:build-1
  #  volumes:
  #    - ./configs:/a:ro
volumes:
  files:
  caddy:
