version: '3'
services:
  http:
    image: femiwiki/caddy:1.0.3
    ports:
      - 80:80
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile:ro
      - files:/srv/femiwiki.com
  fastcgi:
    image: femiwiki/mediawiki:build-19
    volumes:
      - ./configs:/a:ro
      - files:/srv/femiwiki.com
  parsoid:
    image: femiwiki/parsoid:build-0
  ## 잠시 끔. https://github.com/femiwiki/femiwiki/issues/82 참고
  #restbase:
  #  image: femiwiki/restbase:build-1
  #  volumes:
  #    - ./configs:/a:ro
volumes:
  files:
