version: '3'
services:
  http:
    image: femiwiki/caddy:1.0.3
    ports:
      - 80:80
      - 443:443
    volumes:
      # 임시로 dev 사용
      - ./caddy/Caddyfile.dev:/etc/Caddyfile:ro
      - files:/srv/femiwiki.com
      - caddy:/etc/caddycerts
    environment:
      - CADDYPATH=/etc/caddycerts
  fastcgi:
    image: femiwiki/mediawiki:build-20
    volumes:
      - ./configs:/a:ro
      - files:/srv/femiwiki.com
  parsoid:
    image: femiwiki/parsoid:build-0
  restbase:
   image: femiwiki/restbase:build-2
   volumes:
     - ./configs:/a:ro
volumes:
  files:
  caddy:
