version: '3'
services:
  http:
    image: joshix/caddy:v0.11.3
    ports:
      - 80:80
    volumes:
      - ./caddy:/var/www/html:ro
      - files:/srv/femiwiki.com
  fastcgi:
    image: femiwiki/mediawiki:build-8
    volumes:
      - ./configs:/a:ro
      - files:/srv/femiwiki.com
  parsoid:
    image: femiwiki/parsoid:build-0
  restbase:
    image: femiwiki/restbase:build-1
    volumes:
      - ./configs:/a:ro
volumes:
  files:
