version: '3'
services:
  http:
    image: femiwiki/caddy:1.0.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile.prod:/etc/Caddyfile:ro
      - files:/srv/femiwiki.com
      - caddy:/etc/caddycerts
    environment:
      - CADDYPATH=/etc/caddycerts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  fastcgi:
    image: femiwiki/mediawiki:build-26
    volumes:
      - ./configs:/a:ro
      - files:/srv/femiwiki.com
      - l18n_cache:/tmp/cache
  mysql:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/etc/mysql/conf.d:ro
      - /srv/mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  memcached:
    image: memcached:1.5.17-alpine
  parsoid:
    image: femiwiki/parsoid:build-0
  ## 잠시 끔. https://github.com/femiwiki/femiwiki/issues/82 참고
  #restbase:
  #  image: femiwiki/restbase:build-1
  #  volumes:
  #    - ./configs:/a:ro
  #cassandra:
  #  image: femiwiki/cassandra:build-0
  #  volumes:
  #    - cassandra:/var/lib/cassandra
volumes:
  files:
  caddy:
  l18n_cache:
