version: '3'
services:
  http:
    image: femiwiki/caddy:1.0.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile.prod:/etc/Caddyfile:ro
      - files:/srv/femiwiki.com
      - caddy:/etc/caddycerts
    environment:
      - CADDYPATH=/etc/caddycerts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  fastcgi:
    image: femiwiki/mediawiki:202002181527326c87e3
    volumes:
      - ./configs:/a:ro
      - files:/srv/femiwiki.com
      - l18n_cache:/tmp/cache
      ## 스킨 등 개발할 때엔 아래 라인을 주석해제
      # - ../skin:/srv/femiwiki.com/skins/Femiwiki
      # - ../UnifiedExtensionForFemiwiki:/srv/femiwiki.com/extensions/UnifiedExtensionForFemiwiki
  parsoid:
    image: femiwiki/parsoid:build-2
  restbase:
    image: femiwiki/restbase:build-2
    environment:
      # Workaround for https://github.com/femiwiki/femiwiki/issues/151
      - MEDIAWIKI_APIS_URI=https://femiwiki.com/api.php
    volumes:
      - /srv/restbase.sqlite3:/srv/restbase/db.sqlite3
  mysql:
    image: mysql:8.0.17
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/etc/mysql/conf.d:ro
      - /srv/mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  memcached:
    image: memcached:1.5.17-alpine

volumes:
  files:
  caddy:
  l18n_cache:
