version: '3'
services:
  http:
    image: ghcr.io/femiwiki/mediawiki:2021-01-03T11-48-c3b6669f
    command: caddy run
    ports:
      - 80:80
      - 443:443
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - caddy:/etc/caddycerts
    environment:
      - CADDYPATH=/etc/caddycerts
      - FASTCGI_ADDR=fastcgi:9000
      - RESTBASE_ADDR=restbase:7231
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  fastcgi:
    image: ghcr.io/femiwiki/mediawiki:2021-01-03T11-48-c3b6669f
    volumes:
      - ./configs:/a:ro
      - l18n_cache:/tmp/cache
  parsoid:
    image: ghcr.io/femiwiki/parsoid:2020-12-10T14-51-f84b9d2d
    environment:
      - MEDIAWIKI_LINTING=true
  restbase:
    image: ghcr.io/femiwiki/restbase:2020-12-13T02-25-8388f4c4
    environment:
      # Workaround for https://github.com/femiwiki/femiwiki/issues/151
      - MEDIAWIKI_APIS_URI=https://femiwiki.com/api.php
    volumes:
      - /srv/restbase.sqlite3:/srv/restbase/db.sqlite3
  mathoid:
    image: ghcr.io/femiwiki/mathoid:2020-12-09T04-56-c3db867c
  mysql:
    image: mysql:8.0.21
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/etc/mysql/conf.d:ro
      - /srv/mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  memcached:
    image: memcached:1.6.6-alpine

volumes:
  caddy:
  l18n_cache:
