name: docker-php-fpm
inputs:
  version:
    required: true
  push:
    required: false
    default: false
runs:
  using: composite
  steps:
    - uses: docker/build-push-action@v6
      with:
        context: '{{ defaultContext }}:dockers/php-fpm'
        platforms: linux/amd64,linux/arm64
        cache-from: ghcr.io/femiwiki/php-fpm:latest
        load: false
        push: ${{ inputs.push }}
        tags: |
          ghcr.io/femiwiki/php-fpm:latest
          ghcr.io/femiwiki/php-fpm:${{ inputs.version }}
