name: docker-caddy
inputs:
  version:
    required: true
  push:
    required: false
    default: false
runs:
  using: composite
  steps:
    - uses: docker/build-push-action@v6
      with:
        context: '{{ defaultContext }}:dockers/caddy'
        platforms: linux/amd64,linux/arm64
        cache-from: ghcr.io/femiwiki/caddy:latest
        load: false
        push: ${{ inputs.push }}
        tags: |
          ghcr.io/femiwiki/caddy:latest
          ghcr.io/femiwiki/caddy:${{ inputs.version }}
