name: docker-femiwiki-extensions
inputs:
  version:
    required: true
  push:
    required: false
    default: false
runs:
  using: composite
  steps:
    - uses: docker/build-push-action@v6
      with:
        context: '{{ defaultContext }}:dockers/femiwiki-extensions'
        platforms: linux/amd64
        cache-from: ghcr.io/femiwiki/femiwiki-extensions:latest
        load: false
        push: ${{ inputs.push }}
        tags: |
          ghcr.io/femiwiki/femiwiki-extensions:latest
          ghcr.io/femiwiki/femiwiki-extensions:${{ inputs.version }}
