#!/bin/bash

# 주기적으로 실행해야하는 스크립트. 미디어위키의 시스템 메시지를 항상 최신으로
# 유지시켜 준다.
#
# Reference:
#   https://www.mediawiki.org/wiki/Extension:LocalisationUpdate
#   https://wikitech.wikimedia.org/wiki/LocalisationUpdate

set -euo pipefail; IFS=$'\n\t'

echo "Starting LU at $(date --iso-8601=minutes)"
# Update l10n cache
cd /srv/femiwiki.com/extensions/LocalisationUpdate

sudo nice -n 19 php update.php
sudo nice -n 19 php update.php --repoid femiwiki
echo "All done at $(date --iso-8601=minutes)"
