#!/bin/bash

# 주기적으로 실행해야하는 스크립트. 미디어위키의 시스템 메시지를 항상 최신으로
# 유지시켜 준다.
#
# Reference:
#   https://www.mediawiki.org/wiki/Extension:LocalisationUpdate
#   https://wikitech.wikimedia.org/wiki/LocalisationUpdate

set -euo pipefail; IFS=$'\n\t'

# The configuration in LocalSettings.php should match GITDIR and GITREPOS
GITDIR=/var/lib/l10nupdate/mediawiki
GITURL=https://gerrit.wikimedia.org/r/p/mediawiki
GITREPOS="core	extensions	skins"

# Update i18n messages from git to the HEAD of master, or create the clone if it doesn't exist yet
echo "Updating git clone ..."
for path in $GITREPOS
do
	if [ ! -d $GITDIR/$path ]
	then
		# Create the checkout's parent directory and initial clone
		if mkdir -p $(dirname $GITDIR/$path) &&
			nice -n 19 git clone --depth 1 $GITURL/$path $GITDIR/$path
		then
			echo "Cloned $path"
		else
			echo "Cloning $path FAILED."
			exit 1
		fi
	fi

	cd $GITDIR/$path
	# Update checkout of repo
	if nice -n 19 git pull &&
		nice -n 19 git submodule update --depth --init
	then
		echo "Updated $path"
	else
		echo "Updating $path FAILED."
		exit 1
	fi
done
echo "git clone updated."

# Update l10n cache
cd /srv/femiwiki.com/extensions/LocalisationUpdate

sudo -u www-data nice -n 19 php update.php --quiet
sudo -u www-data nice -n 19 php update.php --repoid femiwiki --quiet
echo "All done"
