<?php
/**
 * Writes a class map of the classes extensions and skins declare through
 * AutoloadNamespaces. MediaWiki finds those by building the PSR-4 path and
 * calling is_file() on it for every class a request loads, and PHP does not
 * cache a lookup that fails, so a page view spent about a fifth of its CPU in
 * the autoloaders. With the map, AutoLoader::find() reads the path from an
 * array instead. See femiwiki/infra#1073.
 *
 * The map gives the file find() would have picked: a longer namespace prefix
 * wins over a shorter one, as in find(), and a class an extension lists in
 * AutoloadClasses is left out so that entry still decides. It is keyed by
 * manifest path, so LocalSettings.php registers only the extensions it loads
 * and class_exists() stays false for one that is installed but not loaded.
 *
 * Usage: php autoload-extensions.php <mediawiki root> <output file>
 */

$root = $argv[1] ?? '/srv/femiwiki.com';
$out = $argv[2] ?? '/etc/mediawiki/autoload-extensions.php';

$manifests = array_merge(
	glob( "$root/extensions/*/extension*.json" ),
	glob( "$root/extensions/*/*/extension*.json" ),
	glob( "$root/skins/*/skin.json" )
);
sort( $manifests );

$namespaces = [];
$declared = [];
foreach ( $manifests as $manifest ) {
	$info = json_decode( file_get_contents( $manifest ), true );
	if ( !is_array( $info ) ) {
		continue;
	}
	$dir = dirname( $manifest );
	foreach ( $info['AutoloadNamespaces'] ?? [] as $prefix => $path ) {
		$real = realpath( "$dir/$path" );
		// find() only matches prefixes that end in a separator
		if ( str_ends_with( $prefix, '\\' ) && $real !== false && is_dir( $real ) ) {
			$namespaces[] = [ $prefix, $real, $manifest ];
		}
	}
	foreach ( $info['AutoloadClasses'] ?? [] as $class => $file ) {
		$declared[$class] = true;
	}
}

// Longest prefix first, so the first file a class gets is the one find() picks
usort( $namespaces, static function ( $a, $b ) {
	return strlen( $b[0] ) <=> strlen( $a[0] ) ?: strcmp( $a[0] . $a[1], $b[0] . $b[1] );
} );

$seen = [];
$map = [];
foreach ( $namespaces as [ $prefix, $base, $manifest ] ) {
	$files = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator( $base, FilesystemIterator::SKIP_DOTS )
	);
	$found = [];
	foreach ( $files as $file ) {
		if ( $file->isFile() && $file->getExtension() === 'php' ) {
			$found[] = $file->getPathname();
		}
	}
	sort( $found );
	foreach ( $found as $path ) {
		$relative = substr( $path, strlen( $base ) + 1, -4 );
		$class = $prefix . strtr( $relative, '/', '\\' );
		if ( !isset( $seen[$class] ) && !isset( $declared[$class] ) ) {
			$seen[$class] = true;
			$map[$manifest][$class] = $path;
		}
	}
}
ksort( $map );

file_put_contents( $out, "<?php\n// Generated by autoload-extensions.php; do not edit.\nreturn " .
	var_export( $map, true ) . ";\n" );
fwrite( STDERR, count( $seen ) . " classes from " . count( $namespaces ) . " namespaces written to $out\n" );
