#!/bin/bash

# Reference:
#   https://www.mediawiki.org/wiki/Manual:runJobs.php

set -euo pipefail; IFS=$'\n\t'

cd /srv/femiwiki.com

php maintenance/runJobs.php \
  --maxtime 60 \
  --memory-limit max
