name: Submit a PR for bumping extension

on:
  repository_dispatch:
    types: [bump-extension]

  workflow_dispatch:
    inputs:
      ext:
        description: The name of extension or skin
        type: string

      ver:
        description: The version released
        type: string

jobs:
  bump-extension:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
        with:
          ruby-version: '3.1'

      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        id: vars
        env:
          CLIENT_PAYLOAD_EXTENSION: ${{ github.event.client_payload.extension }}
          CLIENT_PAYLOAD_VERSION: ${{ github.event.client_payload.version }}
          INPUT_EXT: ${{ github.event.inputs.ext }}
          INPUT_VER: ${{ github.event.inputs.ver }}
        with:
          script: |
            return {
              ext: process.env.CLIENT_PAYLOAD_EXTENSION || process.env.INPUT_EXT,
              ver: process.env.CLIENT_PAYLOAD_VERSION || process.env.INPUT_VER,
            }

      - name: Update extensions.json
        env:
          EXT: ${{ fromJSON(steps.vars.outputs.result).ext }}
          VER: ${{ fromJSON(steps.vars.outputs.result).ver }}
        run: ruby .github/bump_extension.rb "$EXT" "$VER"

      - name: Update README
        uses: ./.github/actions/add-changelog-entry
        with:
          image: femiwiki-extensions
          message: Bump ${{fromJSON(steps.vars.outputs.result).ext}} to ${{fromJSON(steps.vars.outputs.result).ver}}

      - uses: peter-murray/workflow-application-token-action@cb731e00cb6754f584507134ff389dfb3dc42bbc # v5.1.0
        if: ${{ github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main' }}
        id: get_workflow_token
        with:
          application_id: ${{ vars.PAT_APPLICATION_ID }}
          application_private_key: ${{ secrets.PAT_APPLICATION_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          commit-message: Bump ${{fromJSON(steps.vars.outputs.result).ext}} to ${{fromJSON(steps.vars.outputs.result).ver}}
          title: Bump ${{fromJSON(steps.vars.outputs.result).ext}} to ${{fromJSON(steps.vars.outputs.result).ver}}
          branch: bump-${{fromJSON(steps.vars.outputs.result).ext}}
