name: Docker

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  docker-images:
    name: Docker image test and publishing
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build a multi-platform docker image and push
        uses: docker/build-push-action@v5
        with:
          context: '{{ defaultContext }}:dockers/${{ inputs.image }}'
          platforms: linux/amd64,linux/arm64
          cache-from: ghcr.io/femiwiki/${{ inputs.image }}:latest
          load: false
          push: ${{ github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/femiwiki/${{ inputs.image }}:latest
            ghcr.io/femiwiki/${{ inputs.image }}:${{ inputs.tag }}
