name: 'Docker: php-fpm'

on:
  push:

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
        if: false

      - uses: docker/setup-buildx-action@v3
        if: false

      - uses: docker/login-action@v3
        if: false && github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: get-version
        run: echo "ver=$(grep -m 1 '## v' dockers/php-fpm/README.md | cut -d'v' -f2)" >> $GITHUB_OUTPUT

      - uses: ./.github/actions/docker-php-fpm
        if: false
        with:
          version: ${{ steps.get-version.outputs.ver }}
          push: ${{ github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main' }}

      - uses: ./.github/actions/add-nev-version-entry-to-changelog
        if: true || ${{ github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main' }}
        with:
          version: ${{ steps.get-version.outputs.ver }}
          upstream: php-fpm
          downstream: mediawiki

      - uses: peter-murray/workflow-application-token-action@v4
        id: get_workflow_token
        with:
          application_id: ${{ secrets.PAT_APPLICATION_ID }}
          application_private_key: ${{ secrets.PAT_APPLICATION_PRIVATE_KEY }}

      - name: Create Pull Request
        id: create-pull-request
        if: true || ${{ github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main' }}
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          commit-message: Bump php-fpm docker image
          title: 'mediawiki: Bump php-fpm docker image'
          branch: bump-php-fpm-v${{ steps.get-version.outputs.ver }}-femiwiki

      - name: Enable Pull Request Automerge
        if: true || ${{ github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main' }}
        run: gh pr merge --merge --auto ${{ steps.create-pull-request.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
