name: 'Docker: mediawiki'

env:
  TAG: '2.0.1'

on:
  push:
    paths:
      - 'dockers/mediawiki/**'
      - .github/workflows/docker-mediawiki.yml
  pull_request:
    paths:
      - 'dockers/mediawiki/**'
      - .github/workflows/docker-mediawiki.yml
  workflow_dispatch:

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        if: github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: '{{ defaultContext }}:dockers/mediawiki'
          platforms: linux/amd64,linux/arm64
          cache-from: ghcr.io/femiwiki/mediawiki:latest
          load: false
          push: ${{ github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/femiwiki/mediawiki:latest
            ghcr.io/femiwiki/mediawiki:${{ env.TAG }}
