name: 'Docker: mediawiki'

on:
  push:
    paths:
      - 'dockers/mediawiki/**'
      - .github/workflows/docker-mediawiki.yml
  pull_request:
    paths:
      - 'dockers/mediawiki/**'
      - .github/workflows/docker-mediawiki.yml
  workflow_dispatch:

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        if: github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: get-version
        run: echo "ver=$(grep -m 1 '## v' dockers/mediawiki/README.md | cut -d'v' -f2)" >> $GITHUB_OUTPUT

      - uses: docker/build-push-action@v6
        with:
          context: '{{ defaultContext }}:dockers/mediawiki'
          platforms: linux/amd64,linux/arm64
          cache-from: ghcr.io/femiwiki/mediawiki:latest
          load: false
          push: ${{ github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/femiwiki/mediawiki:latest
            ghcr.io/femiwiki/mediawiki:${{ steps.get-version.outputs.ver }}

      - uses: ./.github/actions/add-nev-version-entry-to-changelog
        if: ${{ github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main' }}
        with:
          version: ${{ steps.get-version.outputs.ver }}
          upstream: mediawiki
          downstream: femiwiki

      - uses: peter-murray/workflow-application-token-action@v4
        if: ${{ github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main' }}
        id: get_workflow_token
        with:
          application_id: ${{ vars.PAT_APPLICATION_ID }}
          application_private_key: ${{ secrets.PAT_APPLICATION_PRIVATE_KEY }}

      - name: Create Pull Request
        id: create-pull-request
        if: ${{ github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main' }}
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          commit-message: Bump mediawiki docker image
          title: 'femiwiki: Bump mediawiki docker image to v${{ steps.get-version.outputs.ver }}'
          branch: bump-mediawiki-v${{ steps.get-version.outputs.ver }}-femiwiki
