name: 'Docker: mediawiki'

on:
  push:
    paths:
      - 'dockers/mediawiki/**'
      - .github/workflows/docker-mediawiki.yml
  pull_request:
    paths:
      - 'dockers/mediawiki/**'
      - .github/workflows/docker-mediawiki.yml
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.get-version.outputs.ver }}
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        run: echo "ver=$(grep -m 1 '## v' dockers/mediawiki/README.md | cut -d'v' -f2)" >> $GITHUB_OUTPUT

  build:
    needs: get-version
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            os: ubuntu-latest
          - platform: linux/arm64
            os: ubuntu-latest-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        if: github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: '{{ defaultContext }}:dockers/mediawiki'
          platforms: ${{ matrix.platform }}
          cache-from: type=registry,ref=ghcr.io/femiwiki/mediawiki:latest
          load: false
          push: ${{ github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/femiwiki/mediawiki:${{ needs.get-version.outputs.ver }}-${{ replace(matrix.platform, 'linux/', '') }}
            ghcr.io/femiwiki/mediawiki:latest-${{ replace(matrix.platform, 'linux/', '') }}

  push-manifest:
    needs: [get-version, build]
    runs-on: ubuntu-latest
    if: github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push manifest
        run: |
          docker manifest create ghcr.io/femiwiki/mediawiki:latest ghcr.io/femiwiki/mediawiki:latest-amd64 ghcr.io/femiwiki/mediawiki:latest-arm64
          docker manifest push ghcr.io/femiwiki/mediawiki:latest
          docker manifest create ghcr.io/femiwiki/mediawiki:${{ needs.get-version.outputs.ver }} ghcr.io/femiwiki/mediawiki:${{ needs.get-version.outputs.ver }}-amd64 ghcr.io/femiwiki/mediawiki:${{ needs.get-version.outputs.ver }}-arm64
          docker manifest push ghcr.io/femiwiki/mediawiki:${{ needs.get-version.outputs.ver }}

      - uses: ./.github/actions/add-nev-version-entry-to-changelog
        with:
          version: ${{ needs.get-version.outputs.ver }}
          upstream: mediawiki
          downstream: femiwiki

      - uses: peter-murray/workflow-application-token-action@v4
        id: get_workflow_token
        with:
          application_id: ${{ vars.PAT_APPLICATION_ID }}
          application_private_key: ${{ secrets.PAT_APPLICATION_PRIVATE_KEY }}

      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          commit-message: Bump mediawiki docker image
          title: 'femiwiki: Bump mediawiki docker image to v${{ needs.get-version.outputs.ver }}'
          branch: bump-mediawiki-v${{ needs.get-version.outputs.ver }}-femiwiki
