name: Lint, test and publish

on: [push, pull_request]

jobs:
  lint:
    name: PHP lint
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP Action
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
        tools: composer:v1
    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - run: |
        composer install --prefer-source --quiet --no-interaction
        composer test

  docker_image:
    name: Docker image test and publishing
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Edit configuration
      run: |
        mv configs/secret.php.example configs/secret.php;
        sed -i 's~http://localhost~http://127.0.0.1~' development.yml
        sed -i -r 's~ghcr\.io\/femiwiki\/mediawiki:.+~ghcr\.io\/femiwiki\/mediawiki:docker-test~' development.yml

    - run: echo "::set-output name=version::$(date +%Y-%m-%dT%H-%M)-$(echo ${{ github.sha }} | cut -c1-8)"
      id: version

    - name: Build docker image using cache
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker pull ghcr.io/femiwiki/mediawiki:latest
        docker build \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from ghcr.io/femiwiki/mediawiki:latest \
          --tag ghcr.io/femiwiki/mediawiki:latest \
          --tag ghcr.io/femiwiki/mediawiki:docker-test \
          --tag ghcr.io/femiwiki/mediawiki:${{ steps.version.outputs.version }} \
          .

    - name: Initialize docker swarm and start services
      run: |
        docker swarm init
        docker stack deploy -c development.yml mediawiki

    - name: Access 127.0.0.1 until success
      timeout-minutes: 3
      run: |
        echo 'Waiting for http...'
        until curl -sLfo /dev/null 127.0.0.1; do
          sleep 1;
        done;
    - name: Test Parsoid API
      run: |
        URL="http://127.0.0.1/api.php?action=visualeditor&format=json&page=arbitrary_page&paction=parse&wikitext=arbitrary"
        [[ ! "$(curl -s "$URL")" = *\"error\"* ]]
    - name: backup of failure
      if: ${{ failure() }}
      run: |
        echo 'Failed to connect to 127.0.0.1';
        curl -sLfo /dev/null localhost; echo $?
        docker ps;
        for s in $(docker service ls -q ); do docker service ps "$s"; done
        docker container ps;
        for s in $(docker service ls -q ); do docker service logs "$s"; done
    - name: Check if the container is still up
      run: test "$(docker service ps -qf 'desired-state=Running' -f 'desired-state=Ready' mediawiki_fastcgi)"
    - name: Try to access the mediawiki
      run: curl -sSLvo /dev/null 127.0.0.1 || docker service logs mediawiki_fastcgi

    - name: Login to GitHub Container Registry
      if: github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: femiwiki-bot
        password: ${{ secrets.CR_PAT }}

    - name: Publish to Registry
      # Publish only when in the default branch
      if: github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main'
      run: |
        docker push ghcr.io/femiwiki/mediawiki:latest
        docker push ghcr.io/femiwiki/mediawiki:${{ steps.version.outputs.version }}
